{
 "title": "API.Camp::Load Test Dashboard",
 "time": { "from": "2019-11-21T15:09:00.000Z", "to": "2019-11-21T15:17:00.000Z" },
 "panels": [
  {
   "title": "Avg Latency by Simulation ID",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(ac_load_req_duration_ms_sum) by (simId) / sum(ac_load_req_duration_ms_count) by (simId)",
     "legendFormat": "{{simId}}"
    }
   ]
  },
  {
   "title": "Load Server Status Count by Simulation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ac_load_req_duration_ms_count) by (simId, status)",
     "legendFormat": "[{{status}}] {{simId}}"
    }
   ]
  },
  {
   "title": "Avg Latency by Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(ac_load_req_duration_ms_sum) by (simId, status) / sum(ac_load_req_duration_ms_count) by (simId, status)",
     "legendFormat": "[{{status}}] {{simId}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_sum{job=\"api-camp-data-server\"}) / sum(http_server_requests_seconds_count{job=\"api-camp-data-server\"})",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "URI Status Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{job=\"api-camp-data-server\"}[1m])) by (status, uri)",
     "legendFormat": "[{{status}}] {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Live JVM Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "{{job}}" }
   ]
  }
 ]
}